# config.yaml
# ────── add a defaults list (optional, but recommended)
defaults:
  - _self_


seed: 42

training:
  path: /cfs/home/jahj0154/Data/JOLTEON_V1_PREPROCESSED
  data_settings:
    steps_per_epoch: 120
    num_full_passes: 10
    batch_size: 64
    shuffle: True
    num_workers: 0
    pin_memory: False
    sample_redshift: True
    sample_redshift_probs: [1.0, 0.0, 0.0]
    max_obs: False
  loss_settings:
    loss_components:
      - temporal_cross_entropy_loss
    loss_modifiers: null
    loss_modifier_kwargs:
      class_weights:
        - 0.00129985
        - 0.00101030
        - 0.001
        - 0.001
        - 0.00120336
        - 0.00100001
        - 0.05047666
        - 0.00137224
        - 0.00243331
        - 0.00175379
        - 0.00157785
    loss_fn_kwargs: {}
    metric_fns:
      - temporal_predictions
    metric_fn_kwargs: {}
    temporal_weight_fns: unit_weight_fn
    temporal_weight_fn_kwargs:
      gamma: 0.5
  lr_schedule_fn: warmup_cosine_decay_schedule
  num_warmup_epochs: 5
  lr_schedule_settings:
    init_value: 1e-6 # Initial learning rate
    peak_value: 2e-3 # Peak learning rate
    end_value: 1e-6 # Final learning rate
  optimizer_fn: adamw
  training_settings:
    patience: 10
    verbose_steps: True
    verbose_epochs:

model:
  name: specz_xe_loss_64
  save_dir: /cfs/home/jahj0154/StrongLensingNCDE/Results
  save_path: "${model.save_dir}/${model.name}"
  class: PoolingONCDEClassifier
  hyperparams:
    input_feature_size: 33
    representation_size: 8
    ncde_width: 128
    ncde_depth: 1
    ncde_solver: Tsit5     # you can still pass these as strings…
    ncde_adjoint: ReversibleAdjoint
    ncde_max_steps: 1048576
    classifier_width: 128
    classifier_depth: 2
    num_classes: 11
    ncde_rtol: 1e-3
    ncde_atol: 1e-3

range_finding:
  num_steps: 200
  lr_min: 1e-7
  lr_max: 1.0
  repeats: 10
  optimizer: adamw